### ISSUE TITLE
[TASK] Add quiz questions for foundation modules

### ISSUE THREAD

**Issue by aabouzaid** [DevOpsHiveHQ/dynamic-devops-roadmap#10]
Based on PR no. #9, we can embed quizzes on the roadmap website.

Using the JSON format of [react-quiz-component](https://github.com/wingkwong/react-quiz-component), each module should have:

- 50-100 questions about the roadmap.
- The questions shown every time should be 20.
- The questions and the answers are shuffled.

Note that the quiz differs from the [interview questions](https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/issues/3).

**Comment by msaraya** [comment]
I created a PR with the requirements [https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/13](added: quiz questions)
