### ISSUE TITLE
[TASK] Collect top DevOps interview questions and answers

### ISSUE THREAD

**Issue by aabouzaid** [DevOpsHiveHQ/dynamic-devops-roadmap#3]
I got many requests to create a list of DevOps interview questions and answers.
This can be done in parallel while I work on the rest of the roadmap (by today, September 2024, 60% of the roadmap is done).

I'd like to delegate this to someone to speed up the process.

**Comment by msaraya** [comment]
I will pick up this task, I will soon provide an estimation time and expected delivery for it

**Comment by elacheche** [comment]
👋

**Comment by pooriaghaedi** [comment]
I can also work on this.

**Comment by aabouzaid** [comment]
@msaraya @elacheche @pooriaghaedi Thanks for your interest. :raised_hands: 
I've assigned this task to you. Feel free to use any method of collaboration.
You can use the [DevOps Hive Telegram group](https://t.me/DevOpsHive/2073) as a starting point for the kick-off.

**Comment by elacheche** [comment]
Just for logging purpose, this is related to #4

**Comment by aabouzaid** [comment]
@msaraya @elacheche @pooriaghaedi I've created the structure for the [interview section](https://roadmap.devopshive.net/category/interview).

Do you have a timeline for working on that part?

**Comment by aabouzaid** [comment]
Closing this task as it's done by @AyaAboZied and @Mohamed-abdalazez :raised_hands: 

- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/16
- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/15
- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/18
- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/19
- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/20
- https://github.com/DevOpsHiveHQ/dynamic-devops-roadmap/pull/17
